Repository Tyrrrz/DiscordChatExporter, pull requests merged in 2021-07, with the labels that each got.

#622 Filter which messages are exported
  DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs
  DiscordChatExporter.Core/DiscordChatExporter.Core.csproj
  DiscordChatExporter.Core/Exporting/ChannelExporter.cs
  DiscordChatExporter.Core/Exporting/ExportRequest.cs
  DiscordChatExporter.Core/Exporting/Filtering/BinaryExpressionKind.cs
  DiscordChatExporter.Core/Exporting/Filtering/BinaryExpressionMessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/ContainsMessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/FromMessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/HasMessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/MentionsMessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/MessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/NegatedMessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/NullMessageFilter.cs
  DiscordChatExporter.Core/Exporting/Filtering/Parsing/FilterParser.cs
  DiscordChatExporter.Core/Exporting/Filtering/Parsing/FilterToken.cs
  DiscordChatExporter.Core/Exporting/Filtering/Parsing/FilterTokenizer.cs
  DiscordChatExporter.Core/Utils/Polyfills.cs
  DiscordChatExporter.Gui/Services/SettingsService.cs
  DiscordChatExporter.Gui/ViewModels/Dialogs/ExportSetupViewModel.cs
  DiscordChatExporter.Gui/ViewModels/RootViewModel.cs
  DiscordChatExporter.Gui/Views/Dialogs/ExportSetupView.xaml
Labels: enhancement

#639 Update the in-app instructions for getting user token
  DiscordChatExporter.Cli/Commands/GuideCommand.cs
  DiscordChatExporter.Gui/Views/RootView.xaml
Labels: docs, enhancement

#644 Hide author icon when loading returns an error
  DiscordChatExporter.Core/Exporting/Writers/Html/MessageGroupTemplate.cshtml
Labels: enhancement, format/html
