Repository Tyrrrz/DiscordChatExporter, pull requests merged in 2022-06, with the labels that each got.

#864 Make messages linkable in HTML
  DiscordChatExporter.Core/Exporting/Writers/Html/MessageGroupTemplate.cshtml
  DiscordChatExporter.Core/Exporting/Writers/Html/PreambleTemplate.cshtml
Labels: enhancement

#865 Fix Twemoji URLs with ZWJs being generated incorrectly
  DiscordChatExporter.Core/Discord/Data/Emoji.cs
Labels: bug, format/html

#867 Update guide to direct users to the Advanced section of Discord settings rather than appearance
  DiscordChatExporter.Cli/Commands/GuideCommand.cs
Labels: bug, app/cli

#869 Add filename token for current date
  DiscordChatExporter.Core/Exporting/ExportRequest.cs
Labels: enhancement
