Repository Tyrrrz/DiscordChatExporter, pull requests merged in 2023-01, with the labels that each got.

#980 Remove regex check in `Snowflake.TryParse`
  DiscordChatExporter.Core/Discord/Snowflake.cs
Labels: enhancement

#991 Move wiki inside the repository
  .docs/Docker-usage-instructions.md
  .docs/GUI,-CLI-and-Formats-explained.md
  .docs/Install-.NET-Core-runtime.md
  .docs/Linux-usage-instructions.md
  .docs/Message-filters.md
  .docs/Obtaining-Token-and-Channel-IDs.md
  .docs/Readme.md
  .docs/Scheduling-exports-on-Windows.md
  .docs/Scheduling-exports-on-macOS.md
  .docs/Scheduling-exports-with-Cron.md
  .docs/Troubleshooting.md
  .docs/macOS-usage-instructions.md
  .github/ISSUE_TEMPLATE/config.yml
  DiscordChatExporter.Cli/Commands/GuideCommand.cs
  DiscordChatExporter.Gui/App.xaml.cs
  DiscordChatExporter.Gui/ViewModels/Components/DashboardViewModel.cs
  DiscordChatExporter.Gui/Views/Components/DashboardView.xaml
  Readme.md
Labels: enhancement, docs

#993 Update emoji parser to account for miscellaneous characters that are not emojis
  DiscordChatExporter.Core/Markdown/Parsing/MarkdownParser.cs
Labels: bug, format/html
