Repository Tyrrrz/DiscordChatExporter, pull requests merged in 2023-02, with the labels that each got.

#1001 Fix links of group icons
  DiscordChatExporter.Core/Discord/Data/Channel.cs
Labels: bug, format/html

#1002 Improve concurrency handling in `ExportAssetDownloader`
  DiscordChatExporter.Cli.Tests/Infra/ExportWrapper.cs
  DiscordChatExporter.Core/DiscordChatExporter.Core.csproj
  DiscordChatExporter.Core/Exporting/ExportAssetDownloader.cs
Labels: bug

#989 Add option to specify download directory for assets
  DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs
  DiscordChatExporter.Core/Exporting/ExportContext.cs
  DiscordChatExporter.Core/Exporting/ExportRequest.cs
  DiscordChatExporter.Gui/ViewModels/Components/DashboardViewModel.cs
Labels: enhancement, app/cli

#1003 Update to AsyncKeyedLock 6.2.0
  DiscordChatExporter.Core/DiscordChatExporter.Core.csproj
Labels: enhancement
