Repository Tyrrrz/DiscordChatExporter, pull requests merged in 2024-04, with the labels that each got.

#1184 Switched from SemaphoreSlim lock to AsyncNonKeyedLocker
  DiscordChatExporter.Core/DiscordChatExporter.Core.csproj
  DiscordChatExporter.Gui/ViewModels/Framework/DialogManager.cs
Labels: enhancement

#1222 Make the GUI x-platform and adapt the CI/CD pipeline to accommodate that
  .docs/Docker.md
  .docs/Dotnet.md
  .docs/Getting-started.md
  .docs/Linux.md
  .docs/MacOS.md
  .docs/Message-filters.md
  .docs/Readme.md
  .docs/Scheduling-Linux.md
  .docs/Scheduling-MacOS.md
  .docs/Scheduling-Windows.md
  .docs/Token-and-IDs.md
  .docs/Troubleshooting.md
  .docs/Using-the-CLI.md
  .github/workflows/docker.yml
  .github/workflows/main.yml
  DiscordChatExporter.Cli/DiscordChatExporter.Cli.csproj
  DiscordChatExporter.Cli/DiscordChatExporter.Cli.sh
  DiscordChatExporter.Gui/DiscordChatExporter.Gui.csproj
  DiscordChatExporter.Gui/Services/UpdateService.cs
  Readme.md
Labels: enhancement, app/gui

#1223 Set correct file permissions for Linux/OSX release assets
  .github/workflows/main.yml
Labels: bug

#1225 Improve documentation
  .docs/Getting-started.md
  .docs/Using-the-CLI.md
  .docs/Using-the-GUI.md
Labels: enhancement, docs

#1227 Skip invalid reactions instead of crashing
  DiscordChatExporter.Core/Discord/DiscordClient.cs
Labels: bug
